# Generated by Django 3.2.4 on 2021-07-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210728_1725'),
        ('topic', '0002_auto_20210728_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to='accounts.profile'),
        ),
    ]
